{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ include "neuralops.namespace" . }}
  labels:
    {{- include "neuralops.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.storeRef.name }}
    kind: {{ .Values.externalSecrets.storeRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ .Values.secrets.name }}
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DSN
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKey }}
        property: postgres_dsn
    - secretKey: JWT_PRIVATE_KEY_PEM
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKey }}
        property: jwt_private_key_pem
    - secretKey: JWT_PUBLIC_KEY_PEM
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKey }}
        property: jwt_public_key_pem
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKey }}
        property: oidc_client_secret
{{- end }}
