#!/usr/bin/env bash
# Records backup/restore drill metadata for BANK-009 compliance tracking.
set -euo pipefail

OUT="${1:-docs/bank/drill-records/backup-restore-$(date +%Y%m%d).json}"
mkdir -p "$(dirname "$OUT")"

cat >"$OUT" <<EOF
{
  "drillType": "backup-restore",
  "recordedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "environment": "${ENVIRONMENT:-staging}",
  "rpoMinutes": ${RPO_MINUTES:-15},
  "rtoMinutes": ${RTO_MINUTES:-60},
  "status": "${DRILL_STATUS:-simulated}",
  "operator": "${OPERATOR:-platform-sre}",
  "notes": "Generated by scripts/bank-drill-record.sh — attach evidence from BACKUP_RESTORE.md runbook"
}
EOF

echo "Wrote drill record: $OUT"
